os:
  - linux

language: cpp

compiler:
  - clang

# Travis CI has 1.5 cores per VM, take advantage of it
# But first, the makefiles have to be fixed: all plugins are using the same .o's
#env:
#  - MAKEFLAGS="-j 2"

# inpaint plugin requires OpenCV 2.4, but Ubuntu Precise 12.0 only has 2.3.1
# OpenCV 2.4.5 can be found in Kubuntu-ppa Backports
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
  - sudo apt-get update

install:
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev cmake

script:
  - cmake CMakeLists.txt
  - make
