os:
  - linux

language: cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5





    

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

# Travis CI has 1.5 cores per VM, take advantage of it
# But first, the makefiles have to be fixed: all plugins are using the same .o's
#env:
#  - MAKEFLAGS="-j 2"

# inpaint plugin requires OpenCV 2.4, but Ubuntu Precise 12.0 only has 2.3.1
# OpenCV 2.4.5 can be found in Kubuntu-ppa Backports
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
  - sudo apt-get update

install:
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev cmake

script:
  - g++ -v
  - cmake --version
  - cmake CMakeLists.txt
  - make
