# This is a test file containing predefined tests for
# GeKon project

[roulette-simple-mse-dynamic]
selection="roulette"
crossover="simple"
fitness="mse"
mutation="dynamic"
threads=4
max_iterations=1000

[roulette-simple-mse-swap]
selection="roulette"
crossover="simple"
fitness="mse"
mutation="swap"
threads=4
max_iterations=1000

[roulette-simple-ssim-dynamic]
selection="roulette"
crossover="simple"
fitness="ssim"
mutation="dynamic"
threads=4
max_iterations=1000

[roulette-simple-ssim-swap]
selection="roulette"
crossover="simple"
fitness="ssim"
mutation="swap"
threads=4
max_iterations=1000



[roulette-convex-mse-dynamic]
selection="roulette"
crossover="convex"
fitness="mse"
mutation="dynamic"
threads=4
max_iterations=1000

[roulette-convex-mse-swap]
selection="roulette"
crossover="convex"
fitness="mse"
mutation="swap"
threads=4
max_iterations=1000

[roulette-convex-ssim-dynamic]
selection="roulette"
crossover="convex"
fitness="ssim"
mutation="dynamic"
threads=4
max_iterations=1000

[roulette-convex-ssim-swap]
selection="roulette"
crossover="convex"
fitness="ssim"
mutation="swap"
threads=4
max_iterations=1000



[roulette-blx_a-mse-dynamic]
selection="roulette"
crossover="blx_a"
fitness="mse"
mutation="dynamic"
threads=4
max_iterations=1000

[roulette-blx_a-mse-swap]
selection="roulette"
crossover="blx_a"
fitness="mse"
mutation="swap"
threads=4
max_iterations=1000

[roulette-blx_a-ssim-dynamic]
selection="roulette"
crossover="blx_a"
fitness="ssim"
mutation="dynamic"
threads=4
max_iterations=1000

[roulette-blx_a-ssim-swap]
selection="roulette"
crossover="blx_a"
fitness="ssim"
mutation="swap"
threads=4
max_iterations=1000
