# This is a test file containing predefined tests for
# GeKon project

[tournament-simple-mse-dynamic]
selection="tournament"
crossover="simple"
fitness="mse"
mutation="dynamic"
threads=4
max_iterations=500

[tournament-simple-mse-swap]
selection="tournament"
crossover="simple"
fitness="mse"
mutation="swap"
threads=4
max_iterations=500

[tournament-simple-ssim-dynamic]
selection="tournament"
crossover="simple"
fitness="ssim"
mutation="dynamic"
threads=4
max_iterations=500

[tournament-simple-ssim-swap]
selection="tournament"
crossover="simple"
fitness="ssim"
mutation="swap"
threads=4
max_iterations=500



[tournament-convex-mse-dynamic]
selection="tournament"
crossover="convex"
fitness="mse"
mutation="dynamic"
threads=4
max_iterations=500

[tournament-convex-mse-swap]
selection="tournament"
crossover="convex"
fitness="mse"
mutation="swap"
threads=4
max_iterations=500

[tournament-convex-ssim-dynamic]
selection="tournament"
crossover="convex"
fitness="ssim"
mutation="dynamic"
threads=4
max_iterations=500

[tournament-convex-ssim-swap]
selection="tournament"
crossover="convex"
fitness="ssim"
mutation="swap"
threads=4
max_iterations=500



[tournament-blx_a-mse-dynamic]
selection="tournament"
crossover="blx_a"
fitness="mse"
mutation="dynamic"
threads=4
max_iterations=500

[tournament-blx_a-mse-swap]
selection="tournament"
crossover="blx_a"
fitness="mse"
mutation="swap"
threads=4
max_iterations=500

[tournament-blx_a-ssim-dynamic]
selection="tournament"
crossover="blx_a"
fitness="ssim"
mutation="dynamic"
threads=4
max_iterations=500

[tournament-blx_a-ssim-swap]
selection="tournament"
crossover="blx_a"
fitness="ssim"
mutation="swap"
threads=4
max_iterations=500
